<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_DATEPICKER</name>
   <tag></tag>
   <elementGuidId>7d49cd2b-c7e3-4d89-9b74-9a9b9a8f061f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='datepicker']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datepicker > div.thumbnail > div.section-title > h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>768a8bf9-dff3-4734-88e8-a12194a66d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DATEPICKER</value>
      <webElementGuid>43c179a7-80d9-48f0-b1f1-09b406a606ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker&quot;)/div[@class=&quot;thumbnail&quot;]/div[@class=&quot;section-title&quot;]/h1[1]</value>
      <webElementGuid>1e03701d-314b-486f-aca8-5428eda80fe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='datepicker']/div/div/h1</value>
      <webElementGuid>65b799c8-0a34-4a5d-9690-18697e23fa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need to upload a specific file?'])[1]/following::h1[1]</value>
      <webElementGuid>0689dae0-b4b6-4c4e-affe-5e6ded793116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FILE UPLOAD'])[1]/following::h1[1]</value>
      <webElementGuid>f87772ec-3591-474c-bd4b-7e13449d1c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datepicker'])[1]/preceding::h1[1]</value>
      <webElementGuid>ccc25136-b3a2-4e15-ac24-3e566f54ed6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automationteststore'])[1]/preceding::h1[1]</value>
      <webElementGuid>0ccb9926-9009-4368-9695-dce0faa2288b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DATEPICKER']/parent::*</value>
      <webElementGuid>e7f87ec2-566b-4600-9fa6-eaf496b6a4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/a/div/div/h1</value>
      <webElementGuid>534d4e8c-53a3-4814-952c-403ddfd5be33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'DATEPICKER' or . = 'DATEPICKER')]</value>
      <webElementGuid>8b21ca12-25c8-4d58-aeee-8e028f11dcac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
