<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Unassigned_PCT1ocAH</name>
   <tag></tag>
   <elementGuidId>d71c37d9-f479-4199-8c37-e7e60612c78a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PCT1ocAH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='PCT1ocAH']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>fb3f78ba-770e-4ecb-ae78-f728ab892730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PCT1ocAH</value>
      <webElementGuid>cfbddf13-2d7c-4cdf-b029-cee5e8e04958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>282</value>
      <webElementGuid>616b0dc1-9c29-4242-9a39-76f72bb14dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>265</value>
      <webElementGuid>f5cef80a-fb9e-4cf2-8f46-eb9266c316aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PCT1ocAH&quot;)</value>
      <webElementGuid>aa9437fe-013d-43f3-9790-43d1f971a2f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='PCT1ocAH']</value>
      <webElementGuid>eeb61107-17e5-4d0a-b632-44b099ccf26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[7]/div/div[2]/div/div/canvas</value>
      <webElementGuid>12ba197b-1929-4352-bf0b-a4a4542408d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/canvas</value>
      <webElementGuid>5386984c-2e5f-4643-b47c-1a180ff4a011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'PCT1ocAH']</value>
      <webElementGuid>081e7736-c631-4807-adee-4b8c8f68eab4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
