<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Auth0 Simple yet powerful authentication</name>
   <tag></tag>
   <elementGuidId>aedd047a-7b4d-4515-a1e1-99b1e66fa82e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pen-ad']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.PenAd_adWrapper-ZDZpK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5a38cf8-4a89-4fca-a542-5d36057c0406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PenAd_adWrapper-ZDZpK</value>
      <webElementGuid>a6e04f16-7179-48d7-b5f2-09ac007acd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Auth0: Simple yet powerful authentication</value>
      <webElementGuid>1497b66b-7af3-4fb0-879b-19a1b52e4b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pen-ad&quot;)/div[@class=&quot;PenAd_root-FeLwX&quot;]/div[@class=&quot;PenAd_adWrapper-ZDZpK&quot;]</value>
      <webElementGuid>beed3d65-b358-4a33-b112-c83d57848860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pen-ad']/div/div</value>
      <webElementGuid>38fec0cc-1802-4946-94c9-2c5b90a02bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!'])[4]/following::div[6]</value>
      <webElementGuid>bb32c4fe-55bb-4732-a9a3-6fed49341494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[5]/following::div[11]</value>
      <webElementGuid>a1076afd-d904-4228-ab0e-3f0743c4604b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Console'])[1]/preceding::div[8]</value>
      <webElementGuid>b3fd64e5-5334-4634-a86c-6cc887fdf2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div</value>
      <webElementGuid>80e26f75-33cb-4246-8dd6-65397880ba00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Auth0: Simple yet powerful authentication' or . = 'Auth0: Simple yet powerful authentication')]</value>
      <webElementGuid>95fe686d-cd46-40bc-8e86-40c1585aa413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
