<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Inputs</name>
   <tag></tag>
   <elementGuidId>9b1df522-5f38-4233-96ef-cdda8cc0aad7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul/li[27]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(27) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c485f26c-c69e-4300-9edc-fa264956d18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/inputs</value>
      <webElementGuid>5af264d6-b735-464c-a065-e1ca59a5a177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inputs</value>
      <webElementGuid>abd28bc9-ee86-4366-9e53-d5455e0ce1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[1]/li[27]/a[1]</value>
      <webElementGuid>be6ef3ba-9d7e-4404-9886-28176eb9ee38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[27]/a</value>
      <webElementGuid>0d6f4b0c-55e4-4939-90e4-50e279adfa1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Inputs')]</value>
      <webElementGuid>c77a3dc3-9f1f-4213-9c63-09a4ac5c1c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infinite Scroll'])[1]/following::a[1]</value>
      <webElementGuid>e1fd8d5d-8d67-42a2-8ccb-c08f819f9846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hovers'])[1]/following::a[2]</value>
      <webElementGuid>0985fe79-be21-46c6-8be2-0d42abb988f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JQuery UI Menus'])[1]/preceding::a[1]</value>
      <webElementGuid>1db33c31-d1a6-47a2-9f51-be595efcfa2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript Alerts'])[1]/preceding::a[2]</value>
      <webElementGuid>1ea2c243-9f0e-477f-a634-2cdebe4d7023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inputs']/parent::*</value>
      <webElementGuid>837dd8ca-aad4-40c1-a411-f1512d8bda9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/inputs')]</value>
      <webElementGuid>b94f8b93-d2ad-49a1-951a-ed2bff4e647d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[27]/a</value>
      <webElementGuid>36c8a00f-7481-4c0f-97a6-656a6ec7965d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/inputs' and (text() = 'Inputs' or . = 'Inputs')]</value>
      <webElementGuid>c97d4ccb-0f54-4840-9c5e-bf5c13539eca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
