<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ecosystem</name>
   <tag></tag>
   <elementGuidId>db07ec60-16f9-4396-ab4d-68a442c36cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ecosystem-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ecosystem-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da2a34f4-5c07-4311-946a-7d38d27df473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#div-ecosystem</value>
      <webElementGuid>c7e1f54e-b792-4062-8f37-fab86a05a5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ecosystem-link</value>
      <webElementGuid>43087556-db2b-4431-9671-ce30cf476a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-link</value>
      <webElementGuid>6ccc30e3-13ce-4293-89f9-f91ecde78cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>23e5ce23-8681-49d8-8021-4c8b2cdb966d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0955df09-8d6b-483f-907a-85f24f371fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ecosystem</value>
      <webElementGuid>240f264e-cc3c-4141-be42-fbbeaa6b2831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ecosystem</value>
      <webElementGuid>7f340b0a-7371-4e1f-b2da-ab1774397d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ecosystem-link&quot;)</value>
      <webElementGuid>63f545d9-ef2e-4959-adf8-fd4ca572a46a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ecosystem-link']</value>
      <webElementGuid>64f142e7-e2d1-4957-9e85-2a2e1b1cbff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ecosystem')]</value>
      <webElementGuid>51831caf-0757-4e5a-9c20-61ea9bd5db2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CTF'])[1]/following::a[1]</value>
      <webElementGuid>9be332b2-a97e-4298-810a-6729aa230cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning'])[1]/following::a[2]</value>
      <webElementGuid>7c82fa2d-cff1-4f86-8aa7-aa25e561d622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supporters'])[1]/preceding::a[1]</value>
      <webElementGuid>071b7388-5f60-43d3-a224-bc034569113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OWASP Juice Shop'])[1]/preceding::a[2]</value>
      <webElementGuid>9f4a4340-5353-4a68-a8aa-18c44600ebe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ecosystem']/parent::*</value>
      <webElementGuid>ea00df78-6b65-4bdc-aa23-1f92f9eb2d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#div-ecosystem')]</value>
      <webElementGuid>79477355-eb84-442d-9882-373a83c43b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[7]/a</value>
      <webElementGuid>f4748819-87a3-4b94-af51-4a0ecaf29af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#div-ecosystem' and @id = 'ecosystem-link' and (text() = 'Ecosystem' or . = 'Ecosystem')]</value>
      <webElementGuid>171ae31a-b06c-44d5-b3d2-f3f29ec769af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
