<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Drag to change, click to remove_q</name>
   <tag></tag>
   <elementGuidId>b26a6e1c-7e01-461d-beec-3d10eb293ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchboxinput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchboxinput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>923d6030-198e-456d-83cb-53cf56c26768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jslog</name>
      <type>Main</type>
      <value>11886</value>
      <webElementGuid>bf0edd1b-79f4-4f2f-a866-c6bfa50c9d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ydp1wd-haAclf</value>
      <webElementGuid>35e2e487-9bf6-4703-9d74-85eaa898c588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5ea28ca6-cd2a-4b13-9f4c-6add5d54a6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>4d6fef8a-cf99-4128-9412-4cfed4004d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchboxinput</value>
      <webElementGuid>5ab7bd2b-dcdf-42ef-8b9e-b7a751554a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>ef60d6f1-2f43-4091-bf46-4131df4cb27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jstcache</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>d7df57da-b702-4d01-a58f-8725283e0da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>keyup:omnibox.keyUp;input:omnibox.inputDetected;keydown:omnibox.keyDown;focus:omnibox.focus;blur:omnibox.blur</value>
      <webElementGuid>bda329bb-7388-4072-a091-fd21e743af51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchboxinput xiQnY</value>
      <webElementGuid>71cc7e91-759b-40e5-b14e-90d0dc2b7765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsan</name>
      <type>Main</type>
      <value>7.searchboxinput,7.xiQnY,0.jslog,0.aria-controls,0.autocomplete,0.autofocus,0.id,0.name,22.jsaction</value>
      <webElementGuid>e74cd2f0-5663-4df0-978d-b542374bdf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchboxinput&quot;)</value>
      <webElementGuid>4c102c7b-7455-4224-bde8-b38e17e41c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchboxinput']</value>
      <webElementGuid>db2b4548-29a2-47e0-912c-3fbd493fd4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='XmI62e']/input</value>
      <webElementGuid>37da8aa0-a3ed-49b5-a767-132b15223250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>66afdf90-b7e9-4621-9d59-7d5274e0a72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchboxinput' and @name = 'q']</value>
      <webElementGuid>4de90e07-c2c3-429c-8b0d-b31291814086</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
