<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Website_DVeyrd</name>
   <tag></tag>
   <elementGuidId>f4e3d5db-3299-4f04-b61b-887a32164f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='QA0Szd']/div/div/div/div[2]/div/div/div/div/div[2]/div/div[3]/div/div[2]/div[4]/div[2]/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d9900e22-7107-4d84-acfa-000069cfdbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DVeyrd </value>
      <webElementGuid>6dbfb6dd-2e6b-4502-996d-baee5f5a692f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QA0Szd&quot;)/div[1]/div[@class=&quot;XltNde tTVLSc&quot;]/div[@class=&quot;w6VYqd&quot;]/div[@class=&quot;bJzME tTVLSc&quot;]/div[@class=&quot;k7jAl lJ3Kh miFGmb&quot;]/div[@class=&quot;e07Vkf kA9KIf dS8AEf&quot;]/div[@class=&quot;aIFcqe&quot;]/div[@class=&quot;m6QErb WNBkOb&quot;]/div[@class=&quot;m6QErb DxyBCb kA9KIf dS8AEf ecceSd&quot;]/div[@class=&quot;m6QErb DxyBCb kA9KIf dS8AEf ecceSd&quot;]/div[3]/div[@class=&quot;Nv2PK tH5CWc THOPZb&quot;]/div[@class=&quot;bfdHYd Ppzolf OFBs3e&quot;]/div[@class=&quot;lI9IFe&quot;]/div[@class=&quot;Rwjeuc&quot;]/div[@class=&quot;etWJQ jym1ob kdfrQc bWQG4d&quot;]/button[@class=&quot;g88MCb S9kvJb&quot;]/span[@class=&quot;DVeyrd&quot;]</value>
      <webElementGuid>63174528-1394-48b2-b5d8-587bab19e214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='QA0Szd']/div/div/div/div[2]/div/div/div/div/div[2]/div/div[3]/div/div[2]/div[4]/div[2]/div[2]/button/span</value>
      <webElementGuid>2e7c1b5d-7271-460f-b831-fa6d435b447b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[1]/following::span[1]</value>
      <webElementGuid>b813dd57-d28e-4ec0-a586-74398ee347ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⋅ Opens 9 am Mon'])[1]/following::span[2]</value>
      <webElementGuid>bc0b4427-9799-4e19-a6ae-852702ef0ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Directions'])[1]/preceding::span[1]</value>
      <webElementGuid>3fe9f7ad-b5ee-4ce1-b225-a00310c52013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xceedance'])[2]/preceding::span[2]</value>
      <webElementGuid>ca410382-a19d-4161-b197-ea23c2f4857a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/button/span</value>
      <webElementGuid>a7a59acc-c840-401c-a077-6d299544f53a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
