<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AdDelhi USA</name>
   <tag></tag>
   <elementGuidId>044a4af1-d78e-4cfe-b518-923752a47d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sbse11x0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sbse11x0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b126f6f2-eddd-4762-bdef-d6115d17469c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sbse11x0</value>
      <webElementGuid>f327eb9b-4b87-477d-a885-d4b3a5415180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>e2109e96-137a-4a94-a3af-70219e85bd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jstcache</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>2c4efbde-bbaa-4c26-b07d-902a96255d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DgCNMb</value>
      <webElementGuid>af8a0223-609d-4326-9baf-d2104e8523b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsan</name>
      <type>Main</type>
      <value>7.DgCNMb,0.id,0.role</value>
      <webElementGuid>5f9e3743-db3f-4600-bcc5-47bac445a1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AdDelhi USA</value>
      <webElementGuid>4b8011d5-c326-4294-9be0-8ca33ab7314f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sbse11x0&quot;)</value>
      <webElementGuid>cb11abf6-ed92-4f8f-bbea-d9bfa7d2e874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sbse11x0']</value>
      <webElementGuid>9144b53b-0dd2-4285-88c1-4aeaf65b47fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sbse11']/div[2]/div/div/div</value>
      <webElementGuid>a774f557-763f-48f3-a118-8dd46dff40ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add destination'])[1]/following::div[15]</value>
      <webElementGuid>67cd0331-a5d2-4ce2-9193-934e54d23d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::div[92]</value>
      <webElementGuid>97a23a9e-9b9b-4a5b-b163-bc2f185c1133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>dc666a94-757f-481f-ad3b-1ab89acc10ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sbse11x0' and (text() = 'AdDelhi USA' or . = 'AdDelhi USA')]</value>
      <webElementGuid>224756b4-11bb-4a79-8a9a-072f915ed61b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
