<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Google Maps_q</name>
   <tag></tag>
   <elementGuidId>d1bc678e-7ca6-4d7c-832a-9339ff9a7b5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchboxinput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchboxinput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd852c98-0388-461b-a2de-afd52dde1d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jslog</name>
      <type>Main</type>
      <value>11886</value>
      <webElementGuid>c5d754d2-1226-452a-9899-b11b2d974089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ydp1wd-haAclf</value>
      <webElementGuid>6302a75e-36b0-47cd-b3c5-e14681af48af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3ff721b0-8bf2-41bd-8c97-d60cbb73012b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>6cfc8de0-5293-421f-be91-2a6e50effa1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchboxinput</value>
      <webElementGuid>6e4f0140-5dd5-4ec9-892b-42cf205770a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>4fe62872-2e5b-4826-be09-23410593144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jstcache</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>bfbd2fc7-89be-434f-a245-68206a654db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>keyup:omnibox.keyUp;input:omnibox.inputDetected;keydown:omnibox.keyDown;focus:omnibox.focus;blur:omnibox.blur</value>
      <webElementGuid>0fb83c32-9e42-4f20-b8d8-cb2407f00408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchboxinput xiQnY</value>
      <webElementGuid>25ec47b7-c505-4efe-b43e-49a080ffe7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsan</name>
      <type>Main</type>
      <value>7.searchboxinput,7.xiQnY,0.jslog,0.aria-controls,0.autocomplete,0.autofocus,0.id,0.name,22.jsaction</value>
      <webElementGuid>5310ff82-f7f0-4194-8864-75c9224d1735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchboxinput&quot;)</value>
      <webElementGuid>f67f9883-3d16-412e-ae13-0e4b8120fecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchboxinput']</value>
      <webElementGuid>66abb1dd-ab82-4821-b7f7-adb3d9a2cf19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='XmI62e']/input</value>
      <webElementGuid>4cdbc539-7fb1-44e3-9e00-256696273b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>19c03095-085c-4c76-93e6-6dc5f7599ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchboxinput' and @name = 'q']</value>
      <webElementGuid>d3768374-1def-4893-acb4-a9c9d5c73aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
