<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mobile</name>
   <tag></tag>
   <elementGuidId>48163ce3-3790-477c-8be7-4435619aa2ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e949a4a1-e5df-4eb0-8e41-d143b12ae1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#mobile</value>
      <webElementGuid>738b9f8f-c1be-44d9-8a50-ee02cef14c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavAlt-anchor u-b0</value>
      <webElementGuid>7c6a2ca9-9966-4bf6-b1c2-3d10eb0cc2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mobile content</value>
      <webElementGuid>2ec3f2f1-c235-4d16-b61f-32cba00f09fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile</value>
      <webElementGuid>16c87036-6985-48c4-8b8c-b11eccf54e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_T53129E6C012_Col00&quot;)/nav[@class=&quot;NavAlt NavAlt--blue u-bn u-tal u-b0&quot;]/div[@class=&quot;container&quot;]/div[2]/a[@class=&quot;NavAlt-anchor u-b0&quot;]</value>
      <webElementGuid>5568e359-665a-4d4a-b376-ca46fde7d5fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a[3]</value>
      <webElementGuid>f45a357b-7cc7-40c5-81fc-570ddd26249b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mobile')]</value>
      <webElementGuid>93349455-24eb-475d-bbf1-809843905d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desktop'])[2]/following::a[1]</value>
      <webElementGuid>ed53c0e1-dc5a-4b12-bc36-2440b95c6658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web'])[2]/following::a[2]</value>
      <webElementGuid>8746b7e4-6551-4a97-8c6f-812a8b4d013d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporting &amp; QA'])[1]/preceding::a[1]</value>
      <webElementGuid>517d7c3a-2137-4788-979d-bd645b39d28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conversational UI'])[1]/preceding::a[2]</value>
      <webElementGuid>11d6cfdf-52b3-4a25-be4a-81d280dc2017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#mobile')]</value>
      <webElementGuid>d4ed4faa-bc2a-4c31-9f9e-c247ec1e697e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/a[3]</value>
      <webElementGuid>618f42d5-5a8d-4684-8d43-5235db401ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#mobile' and (text() = 'Mobile' or . = 'Mobile')]</value>
      <webElementGuid>3438c8ff-3530-4579-b276-2634b36bdf95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
