<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Goto Home</name>
   <tag></tag>
   <elementGuidId>71fdd3a2-0e9a-436f-8048-3f4626281b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='home']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22599010-e511-44fe-9d8e-4e57f58f56b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>f608c7f1-dd1c-40ac-a955-30018f94cba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>9bb385db-6bb5-4ddb-b9eb-621265a09c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-link</value>
      <webElementGuid>e0ca128f-2feb-48e1-be24-1dfd7d3bab67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce5439c6-5f0f-4927-ae93-b8826ab99d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Goto Home</value>
      <webElementGuid>67f9d36f-e072-4bc7-9f09-570a13b2ddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)</value>
      <webElementGuid>08f4c9d6-617d-4317-9a83-3d9d6732f3fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='home']</value>
      <webElementGuid>0d7bc3fa-c8bf-4d00-bf25-f98d53429727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goto Home and come back here using driver command'])[1]/following::button[1]</value>
      <webElementGuid>f2442e44-a10b-4ee0-b2c5-8c418661af68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Button'])[1]/following::button[1]</value>
      <webElementGuid>2b8ba2e2-9ab1-44b1-8f05-c23c516eb6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get the X &amp; Y co-ordinates'])[1]/preceding::button[1]</value>
      <webElementGuid>d614cb7f-3320-4a86-aecc-3bfec37ca364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Location'])[1]/preceding::button[1]</value>
      <webElementGuid>0ed5bcdb-9e1e-4137-a131-828b72e769ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Goto Home']/parent::*</value>
      <webElementGuid>19a48c68-149c-43b9-a348-b20cdf4634ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0d4efe30-bb59-4a63-8de6-0c7d8c9dcad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'home' and (text() = 'Goto Home' or . = 'Goto Home')]</value>
      <webElementGuid>b47eb82f-24a3-4454-9243-240516961151</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
