<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do this to reduce the number of times_edee07</name>
   <tag></tag>
   <elementGuidId>e11c2ad0-2373-4cff-aa52-345f5771ab7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='KmsiCheckboxField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#KmsiCheckboxField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e8ab085-c448-4c74-a8f0-c9ebb9cc5443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KmsiCheckboxField</value>
      <webElementGuid>05cf8aa3-c3b5-4181-a12a-5124321445c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DontShowAgain</value>
      <webElementGuid>4cf82e10-d9e8-4710-9695-5d98630fde2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9fdef1db-4292-4445-a6e9-f8be0938587c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18621e94-14dd-4abe-87d3-c3608b6a6c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>ariaLabel: str['STR_Kmsi_DontShowAgain']</value>
      <webElementGuid>5fe10180-4966-40de-b8ba-3b273dd7a54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Don't show this again</value>
      <webElementGuid>b36fedfc-c0b9-4930-9ffb-7810db2df76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KmsiCheckboxField&quot;)</value>
      <webElementGuid>d6592e3f-840e-44d7-b002-663470bc7e9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='KmsiCheckboxField']</value>
      <webElementGuid>ab921fcd-83a8-4d58-a2c1-0c78a8ba3594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[3]/div/div[2]/div/div[3]/div/div/label/input</value>
      <webElementGuid>0ddeb019-0637-46be-b59e-6f5fa07da160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>a276cb76-572d-43dd-b557-4952e5635964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'KmsiCheckboxField' and @name = 'DontShowAgain' and @type = 'checkbox']</value>
      <webElementGuid>7a4508a0-2e32-4401-9b7e-aa4b5136cfc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
