<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>39871c3c-5cbe-4246-8036-ba1921c28178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.column > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cef5a3bd-8cdd-45ce-98a9-657668a837cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.buymeacoffee.com/button-api/?text=Buy me a beer&amp;emoji=🍺&amp;slug=letcode&amp;button_colour=FF5F5F&amp;font_colour=ffffff&amp;font_family=Cookie&amp;outline_colour=000000&amp;coffee_colour=FFDD00</value>
      <webElementGuid>9748c76a-0ccc-4218-af07-a65ecbd553c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/app-root[1]/app-main[1]/section[@class=&quot;hero is-medium bg&quot;]/div[@class=&quot;hero-body&quot;]/div[@class=&quot;container has-text-centered&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;column&quot;]/a[1]/img[1]</value>
      <webElementGuid>96535e7b-724f-442e-985c-f81e9b2d3e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>b9512fba-ded7-4e51-a37b-3e383b8e3ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.buymeacoffee.com/button-api/?text=Buy me a beer&amp;emoji=🍺&amp;slug=letcode&amp;button_colour=FF5F5F&amp;font_colour=ffffff&amp;font_family=Cookie&amp;outline_colour=000000&amp;coffee_colour=FFDD00']</value>
      <webElementGuid>5e0761a6-fbe7-4848-a84b-d334fb3d793d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
