<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xceedance DarwinBox SSO</name>
   <tag></tag>
   <elementGuidId>fa8a3d8c-4138-4d9e-ba2d-7d5d4e55664f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='sso_form']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.body.ripple-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f87ac146-7b45-4edc-9e7d-f67761b13c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>624c35a1-3877-40fa-a339-19a7dbb343eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>a649ece62bce4a</value>
      <webElementGuid>20a4d409-0089-4d30-9284-69bf16b6d222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>body ripple-effect</value>
      <webElementGuid>39f51044-7450-40ca-8dda-572cbcb55ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xceedance DarwinBox SSO</value>
      <webElementGuid>10f20599-e157-43da-b7d1-9917c9a70903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sso_form&quot;)/div[@class=&quot;single_sign_on&quot;]/div[@class=&quot;user_login_options mt-24 db-customscrollbar&quot;]/a[@class=&quot;body ripple-effect&quot;]</value>
      <webElementGuid>c8201043-0735-4550-989d-1f52b3a82777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sso_form']/div/div/a</value>
      <webElementGuid>e53c8958-01c2-488e-8908-0a2efcd5d9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xceedance DarwinBox SSO')]</value>
      <webElementGuid>9da70dc0-0f91-44ed-bdcf-00c932d0e083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single sign on'])[1]/following::a[1]</value>
      <webElementGuid>4660279f-67c7-4d08-a75f-258f91d780a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powered By'])[1]/preceding::a[2]</value>
      <webElementGuid>64224db7-19b3-448d-bede-298b0dae8cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xceedance DarwinBox SSO']/parent::*</value>
      <webElementGuid>bf71b911-b0e8-40a6-9432-e9503d883a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>b1f1e6b2-76c3-41de-b10a-8c5eb65e28a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>7fe56223-38e7-4630-819f-f2acd48a33c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Xceedance DarwinBox SSO' or . = 'Xceedance DarwinBox SSO')]</value>
      <webElementGuid>8b5f10a5-c6f0-4d07-8b74-086583f1bb4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
