<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Select Date_glyphicon glyphicon-calendar</name>
   <tag></tag>
   <elementGuidId>3bc02906-3115-4c6e-9299-be6533f15765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datepicker']/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.glyphicon.glyphicon-calendar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>96258438-3de3-4eee-a52d-d6fe74ede0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-calendar</value>
      <webElementGuid>464c913e-d472-4ff5-9aed-b52380a16af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker&quot;)/span[@class=&quot;input-group-addon&quot;]/i[@class=&quot;glyphicon glyphicon-calendar&quot;]</value>
      <webElementGuid>c2c181c0-c23a-432f-adad-6d1a33a67e41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepicker']/span/i</value>
      <webElementGuid>22b4e990-b5b7-44ab-a1f2-b0e1aaec0f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>3cb13ee5-f865-43b7-9803-fbfa27bdd865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
