<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_in</name>
   <tag></tag>
   <elementGuidId>3cfcc8dd-7e6a-41b9-a16c-b8563721f2eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-logo-sprites</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-logo-sprites']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ce8d59a-aa05-4132-89e5-811485ce7cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ref=nav_logo</value>
      <webElementGuid>d652714f-16c6-4b29-b9dc-88cf71ea6169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-logo-sprites</value>
      <webElementGuid>4c31aa23-89c4-498c-a8c2-ee2b5d3d7df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-logo-link nav-progressive-attribute</value>
      <webElementGuid>3cc5a7c1-8554-4a56-8375-7db166ced038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amazon.in</value>
      <webElementGuid>83e16808-3c34-420b-bf87-ad2f961ce07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      
      
      .in
    </value>
      <webElementGuid>b950501c-9986-4dc6-ae40-0fcd91820081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-logo-sprites&quot;)</value>
      <webElementGuid>c96d6892-450a-4cbb-abd2-ed24f76f1a7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-logo-sprites']</value>
      <webElementGuid>35a121ff-a934-4f2f-98ad-60bb2ab06d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-logo']/a</value>
      <webElementGuid>1869299e-490b-424e-a13b-73bb5e436297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::a[1]</value>
      <webElementGuid>cc8fce08-770a-475e-b329-73dd7c6fc47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello'])[1]/preceding::a[1]</value>
      <webElementGuid>a20db4b0-e9e8-403e-bd1d-69f9d8c942ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ref=nav_logo')]</value>
      <webElementGuid>c3399e29-fdec-4828-9a39-31f2e40b2e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>7399c900-7544-46c9-8687-4a05b859d186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ref=nav_logo' and @id = 'nav-logo-sprites' and (text() = '
      
      
      .in
    ' or . = '
      
      
      .in
    ')]</value>
      <webElementGuid>61c61c2a-b0c7-46ba-9414-848725086038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
