<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Update_a-button-input</name>
   <tag></tag>
   <elementGuidId>7a39a0ed-55b2-4bb1-ad85-0db328e3edb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c13c4179-cfb6-43f6-b9fa-8d9a1eb1d7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>f431ac35-7b9a-4a92-a68f-682eec409e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>8fcb5103-c8b0-4b7c-ab93-0c01c888ee70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ea20bef7-ee98-4fb3-be16-94c5740dd483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-item-0c35ff98-d849-4561-9c89-339efaca2e8d&quot;)/div[@class=&quot;a-section a-spacing-none ewc-wider-compact-view-only ewc-item-actions&quot;]/div[@class=&quot;a-row ewc-qty-and-action-items&quot;]/div[@class=&quot;a-column a-span4 a-text-center a-spacing-mini a-spacing-top-base a-span-last&quot;]/div[@class=&quot;a-section a-spacing-base ewc-delete-icon-container&quot;]/span[@class=&quot;a-declarative&quot;]/span[@class=&quot;a-button a-button-base a-button-small a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>42b67ae1-8d05-4cb3-bbb9-cada7a0ecc0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[2]</value>
      <webElementGuid>a8619193-efc1-4e80-9e60-cfe6b336e085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-item-0c35ff98-d849-4561-9c89-339efaca2e8d']/div[3]/div[7]/div[2]/div/span/span/span/input</value>
      <webElementGuid>d0908c37-d8a9-400b-b87d-b7657d2e86f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/input</value>
      <webElementGuid>8c6c2043-1f78-47c3-a367-cb204d13542f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Delete' and @type = 'submit']</value>
      <webElementGuid>1625f1d1-578b-4aba-b167-feceb220dd17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
