<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click</name>
   <tag></tag>
   <elementGuidId>dc009eab-6098-4fab-b8fb-fb90ec3e28a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Click')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1229f5bb-3480-4e31-b271-758eeaeeb7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-footer-item</value>
      <webElementGuid>17953f53-6cd8-4985-94bd-631bb13302f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/buttons</value>
      <webElementGuid>871b359e-aea5-4464-8213-50c013571d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click</value>
      <webElementGuid>1914a217-63df-41c1-83ab-ab0585ac1945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/app-root[1]/app-test-site[1]/section[@class=&quot;hero has-background-white-ter&quot;]/div[@class=&quot;hero-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;columns is-multiline is-mobile&quot;]/div[@class=&quot;column is-3-desktop is-6-tablet&quot;]/app-menu[1]/div[@class=&quot;card&quot;]/footer[@class=&quot;card-footer&quot;]/a[@class=&quot;card-footer-item&quot;]</value>
      <webElementGuid>54acc0ee-ce8a-4a0a-bf08-84379bb11ee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Click')]</value>
      <webElementGuid>13f79429-87ea-42f3-a11c-d0d3e81d2ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interact with different types of buttons'])[1]/following::a[1]</value>
      <webElementGuid>2e21b6d4-4b59-4537-a7b0-12908b95f50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::a[1]</value>
      <webElementGuid>f02e5bf7-5050-4cff-99ef-698e33d6ea18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interact with different types of drop-down'])[1]/preceding::a[1]</value>
      <webElementGuid>51a78619-69dc-4e85-8c9a-7e33e752b51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop-Down'])[1]/preceding::a[1]</value>
      <webElementGuid>5e067270-23c0-4340-b277-936dd15ebba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click']/parent::*</value>
      <webElementGuid>a0da4c26-f856-4d52-9184-37f2d51431ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/buttons')]</value>
      <webElementGuid>c240c74f-4430-4036-a176-e36781a575e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/app-menu/div/footer/a</value>
      <webElementGuid>dc7c9b0b-1f34-4a1e-b3ca-129f0932b030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/buttons' and (text() = 'Click' or . = 'Click')]</value>
      <webElementGuid>fea92e80-40e9-49be-b09c-97fc72b2ba7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
